SELECT P.PRODUCT_CODE, PRICE * SUM(OS.SALES_AMOUNT) AS SALES
       FROM PRODUCT P
       INNER JOIN OFFLINE_SALE OS ON OS.PRODUCT_ID = P.PRODUCT_ID
       GROUP BY PRODUCT_CODE
       ORDER BY SALES DESC, PRODUCT_CODE