SELECT INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
       FROM ICECREAM_INFO II
       INNER JOIN FIRST_HALF FH
       WHERE II.FLAVOR = FH.FLAVOR
       GROUP BY INGREDIENT_TYPE
       ORDER BY TOTAL_ORDER