SELECT CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
       FROM BOOK
       INNER JOIN BOOK_SALES BS 
             ON BS.BOOK_ID = BOOK.BOOK_ID
       WHERE DATE_FORMAT(BS.SALES_DATE, "%y-%m") = '22-01'
       GROUP BY CATEGORY
       ORDER BY CATEGORY