SELECT AI.NAME, AI.DATETIME
       FROM ANIMAL_INS AI
       LEFT JOIN ANIMAL_OUTS AO 
                 ON AI.ANIMAL_ID = AO.ANIMAL_ID
       ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME), AI.DATETIME
       LIMIT 3